spring:
  application:
    name: cokothon

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cokothon?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  forward-headers-strategy: native
  port: 8081
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs